version: '3.8'

services:
  db:
    image: neo4j:5
    container_name: neo4j_db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
    volumes:
      - neo4j_data:/data

  backend:
    build: ./backend
    container_name: music_backend
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend 
    container_name: music_frontend
    ports:
      - "3001:80"     
    depends_on:
      - backend      

volumes:
  neo4j_data: